### ISSUE TITLE
Multiline message support

### ISSUE THREAD

**Issue by JumpyLionnn** [zeondev/lunar#22]
**Is your feature request related to a problem? Please describe.**
Add a multiline textbox for the message input so a message can contain more than 1 line without filling the first one.

**Describe the solution you'd like**
replace the input element by a text area and set some styling

**Describe alternatives you've considered**
replace the input element by an editable div

**Comment by datkat21** [comment]
I think that using a textarea would be easiest. If you view [here](https://getbootstrap.com/docs/4.0/components/forms/#form-controls) on the 4th one you can see textareas are very easy to make.

**Comment by ItsLap** [comment]
Already Implemented thanks to Jumpy
