### ISSUE TITLE
search bar is not filtering new messages

### ISSUE THREAD

**Issue by fwipsity** [zeondev/lunar#4]
when the search bar is not empty and new messages arrived so it still displays them and not filtering them according to the search input.

2 solutions that I can think of:
1. the search gets canceled
2. it will filter those

preferred solution is 2 because people can send message to annoy you and stop your search so you can search a message

**Comment by ItsLap** [comment]
on it

**Comment by ItsLap** [comment]
i may fix it later today though. done alot of coding today 🤣
