### ISSUE TITLE
Bot commands

### ISSUE THREAD

**Issue by ItsLap** [zeondev/lunar#7]
Here is an example of what to respond with

"

Command. !test
Responce. Text

"

**Comment by fwipsity** [comment]
make a privacy setting for being able to see your time like with a !time {user} and them it will write their time zone if they allowed it if not it will say that you cannt use this command on this user or something

**Comment by datkat21** [comment]
Here are my suggestions for commands:

Command | Response
--- | ---
!say {message} | (display the message)
!repo | (link to [this repo](https://github.com/zeondev/lunar))
!suggest | (link to [the issues page](https://github.com/zeondev/lunar/issues/))
I may add more in the future so I will edit this comment.
